### ISSUE TITLE
Printkey is not parallelized

### ISSUE THREAD

**Issue by makitos666** [volatilityfoundation/volatility3#163]
I am trying to extract the entire windows registry from memory, as follows:

`python.exe .\vol.py --parallelism threads -f ..\cridex.vmem windows.registry.printkey.PrintKey --recurse `

As it is a very slow process and I have seen that there is the option to parallelize, because as you can see in the command, I have tried to configure threads.

I have not noticed any difference between parallelizing and not, so I have looked at code.

I have added a check to see if the constants are configured properly:
```
 if sections is None:
            sections = [(self.minimum_address, self.maximum_address - self.minimum_address)]

        sections = list(self._coalesce_sections(sections))
        print(constants.PARALLELISM)
        try:
            progress = DummyProgress()  # type: ProgressValue
            scan_iterator = functools.partial(self._scan_iterator, scanner, sections)
            scan_metric = self._scan_metric(scanner, sections)
```

That's the result:

```
Parallelism.Off
Parallelism.Off
Parallelism.Off
```

I have tried to force the constant, with the following result:

```
Unsatisfied requirement plugins.PrintKey.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PrintKey.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PrintKey.primary', 'plugins.PrintKey.nt_symbols']
```

Is it some kind of error in the code or is it that this part is still in development?

**Comment by ikelos** [comment]
Thanks, that was a good spot!  As it turns out, the code for setting the parallelism from the CLI looked for `threading`, which was not the available option (`threads`) for enabling thread based parallelism.  This has now been fixed in commit `fc005d0`.

Unfortunately, the parallelism may not provide you significant speed benefits.  It's really only used by the scanning engine when scanning chunks of data, so after the automagic is over, it's unlikely this will impact the runtime of plugins that don't do scanning (which I believe printkey does not do).  We also found that the minimal parallelism we could do when scanning generally didn't provide a significant enough speed-up, hence why it's disabled by default.  The last point is that the parallelism only happens when the chunks are being divided and the scan action taken on them, meaning that once a hit has been found, whatever's done to that hit will be in serial.

We are looking for better ways to generally apply parallelism across the codebase, but at the moment the code that's there is the best option we've got.  The slow part is actually the iterator that should generate the addresses to be scanned, but in most implementations that come with python by default (`threading` and `multiprocessing`) they consume the generator entirely in order to evenly balance the work pools (thus negating a great deal of the benefit we could get).  To essentially run a work queue could help us speed up the iteration process and it's something we'll investigate but I'm afraid it's not that high on our priority list.

Hopefully that answers your question?  I'll likely close this in a few days if I don't hear further, because essentially, we know we'd like it faster, we're after that too...  5;)

**Comment by makitos666** [comment]
Thanks for the info. I will look for time to review that particular plugin to see if I find out how to speed up the process, it would be cool to gain speed at that point.

On the other hand, your commit has solved part of the problem, now the parameter works, but the plugin still doesn't work:
```
PS C:\......\volatility3> python.exe .\vol.py --parallelism threads -f ..\cridex.vmem windows.registry.printkey.PrintKey --recurse
Volatility 3 Framework 1.0.0-beta.1

Unsatisfied requirement plugins.PrintKey.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PrintKey.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PrintKey.primary', 'plugins.PrintKey.nt_symbols']
```

**Comment by ikelos** [comment]
Does the plugin work normally without the parallelism?  It looks as though the image isn't being identified properly.  You can try running it with `-vvv` to see more details during the automagic phase...

**Comment by makitos666** [comment]
Yes, it works perfectly without parallelism (I just tried it right now just in case :P)

I attach the verbose output:

```
PS C:\.......\volatility3> python.exe .\vol.py -vvv --parallelism threads -f ..\cridex.vmem windows.registry.printkey.PrintKey --recurse
Volatility 3 Framework 1.0.0-beta.1
INFO     root        : Volatility plugins path: ['C:\\.......\\volatility\\plugins', 'C:\\.......\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\........\\volatility\\symbols', 'C:\\.......\\volatility\\framework\\symbols']
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.statistics
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.certificates
DEBUG    volatility.framework: Importing module: volatility.plugins.configwriter
DEBUG    volatility.framework: Importing module: volatility.plugins.frameworkinfo
DEBUG    volatility.framework: Importing module: volatility.plugins.layerwriter
DEBUG    volatility.framework: Importing module: volatility.plugins.timeliner
DEBUG    volatility.framework: Importing module: volatility.plugins.yarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module yarascan based on file: yarascan
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.bash
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.check_afinfo
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.check_syscall
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.elfs
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.lsmod
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.lsof
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.malfind
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.proc
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.pslist
DEBUG    volatility.framework: Importing module: volatility.plugins.linux.pstree
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.bash
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_syscall
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_sysctl
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.check_trap_table
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.ifconfig
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.lsmod
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.lsof
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.malfind
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.netstat
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.proc_maps
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.psaux
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.pslist
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.pstree
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.tasks
DEBUG    volatility.framework: Importing module: volatility.plugins.mac.trustedbsd
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.callbacks
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module windows.callbacks based on file: windows\callbacks
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.cmdline
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.dlldump
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.dlllist
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.driverirp
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.driverscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.filescan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.handles
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.info
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.malfind
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.moddump
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.modscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.modules
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.mutantscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.poolscanner
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.procdump
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.pslist
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.psscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.pstree
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.ssdt
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.strings
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.svcscan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module windows.svcscan based on file: windows\svcscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.symlinkscan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vaddump
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vadinfo
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.vadyarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module windows.vadyarascan based on file: windows\vadyarascan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.verinfo
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.virtmap
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.hivelist
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.hivescan
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.printkey
DEBUG    volatility.framework: Importing module: volatility.plugins.windows.registry.userassist
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.callbacks, volatility.plugins.windows.svcscan, volatility.plugins.windows.vadyarascan, volatility.plugins.yarascan
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.construct_layers
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.linux
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.mac
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.pdbscan
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.stacker
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.symbol_cache
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.symbol_finder
DEBUG    volatility.framework: Importing module: volatility.framework.automagic.windows
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey
Level 9  volatility.framework.interfaces.configuration: TypeError - offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - key requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - key requirements only accept str type: None
INFO     volatility.framework.automagic: Running automagic: LayerStacker
DEBUG    volatility.framework: Importing module: volatility.framework.layers.crash
DEBUG    volatility.framework: Importing module: volatility.framework.layers.elf
DEBUG    volatility.framework: Importing module: volatility.framework.layers.intel
DEBUG    volatility.framework: Importing module: volatility.framework.layers.lime
DEBUG    volatility.framework: Importing module: volatility.framework.layers.linear
DEBUG    volatility.framework: Importing module: volatility.framework.layers.msf
DEBUG    volatility.framework: Importing module: volatility.framework.layers.physical
DEBUG    volatility.framework: Importing module: volatility.framework.layers.registry
DEBUG    volatility.framework: Importing module: volatility.framework.layers.resources
DEBUG    volatility.framework: Importing module: volatility.framework.layers.segmented
DEBUG    volatility.framework: Importing module: volatility.framework.layers.vmware
DEBUG    volatility.framework: Importing module: volatility.framework.layers.scanners.multiregexp
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
DEBUG    volatility.framework.interfaces.layers: Scan Failure: module 'threading' has no attribute 'Pool'
DEBUG    volatility.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
DEBUG    volatility.framework.interfaces.layers: Scan Failure: module 'threading' has no attribute 'Pool'
INFO     volatility.framework.automagic.linux: No Linux banners found - if this is a linux plugin, please check your symbol files location
INFO     volatility.framework.automagic.mac: No Mac banners found - if this is a mac plugin, please check your symbol files location
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None
INFO     volatility.framework.automagic.pdbscan: No suitable kernels found during pdbscan
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: TypeError - SymbolTableRequirement only accepts string labels: None

Unsatisfied requirement plugins.PrintKey.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PrintKey.nt_symbols: Windows kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
        A file was provided to create this layer (by -f, --single-location or by config)
        The file exists and is readable
        The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PrintKey.primary', 'plugins.PrintKey.nt_symbols']
```

**Comment by ikelos** [comment]
Hmmm, it looks like I made the threading support whilst I was playing with `concurrent.futures` which supports the same interface for both threading and multiprocessing.  Unfortunately, it's not a straight swap for the code we had, although luckily, it is supported in multiprocessing by the little known ThreadPool which uses a dummy process object that uses threads instead.  It's definitely just a stop gap, and once you've tried it I suspect you'll see no speed gains and would therefore highly recommend going back to the well-tested non-parallelised verison (or try your hand at adding in parallelism to the printkey plugin), but for what it's worth, there's a version you can try out in the `threadpool` branch that should support both...

**Comment by makitos666** [comment]
I've been looking at the "printkey" class and it suddenly occurs to me that a good way to implement parallelization could be in the "_registry_walker" function.

Nothing prevents all "hives" from being walked at once (in separate threads).

I think that in this way we would gain speed significantly if we want to dump the entire registry.

I will try to make the implementation and later we will see how we can parallelize the hives themselves, since they are generators

**Comment by ikelos** [comment]
You're right.  You can see how fast dumping a single hive would be by specifying `--offset` after the `windows.registry.printkey` plugin choice.  I suspect that one of the hives (probably HKCR) will take an age, so parallelizing across hives won't offer as huge a benefit as you're suggesting, but it would certainly be an improvement.

Something that might be interesting would be to profile printkey (run it with `python -m cProfile -o output.prof vol.py`) and then view it in something like [snakeviz](http://jiffyclub.github.io/snakeviz/) to see where the bulk of the time's taken?  It may be there's an improvement lurking in the registry code that could provide significant speed-ups to everything?  I suspect I was probably overly cautious in writing the code, so it might do a lot of safety checks which we could ease up on?  When I get some time I'll try to take a look into this...  5:)

**Comment by makitos666** [comment]
Yes, you are right about many things.

The title of the issue was wrong.
Parallelize the hives having one very large and the others relatively much smaller will not make it to end sooner.

But I think I do know where most of the time is spend, in the "TreeGrid" class. To this class, the one that is responsible for the purpose of printing the text on the screen, expects a generator (I suppose because not to load all the results in memory before printing them).

Maybe we could design a system so that not everything resides in a single generator, or use another paradigm with the objective of being able to parallelize this work.

Thanks for listening (reading) me :)

**Comment by ikelos** [comment]
Sure, I'm happy to reconsider the TreeGrid format, but the requirements for it were both to provide access to the results and to be able to provide immediate partial results (hence the generator rather clunkily tacked onto the create of it).  This is so that people using the CLI don't have to wait without knowing what's going on whilst it meticulously populates the Grid with data.  If you can see a way to improve on how to do it I'd be very glad to help implement it?  I haven't looked at the profiling I've done yet, but hopefully I'll get the chance at some point this weekend...  5:)

**Comment by makitos666** [comment]
As you well commented, I used the snakeviz tool to guide me:

![image](https://user-images.githubusercontent.com/3305564/71770363-f6dd0300-2f2b-11ea-9dfd-5beb98f7c248.png)

I confirm that generating the generator is where most of the time is wasted. It does not seem trivial to parallelize this part of the code.

I will continue investigating how we can accelerate this process :P

**Comment by ikelos** [comment]
I've managed to shave a little bit of time off this (multiplied by the number of long keys), by reusing data we already had to vastly reduce the time taken (and essentially remove the `get_key_path` call.  It's only about a 10% increase in mid-cases, but on larger cases it might be slightly quicker than that.  It should take about 2 minutes off your run time (your picture suggests it's sinking 137s into finding the key paths).  I also tried adding caching to the name casting, but it seems that's pretty fast so the results were negligible.  Still, making slight progress...  5:)

**Comment by ikelos** [comment]
A couple more optimizations that shaved a little more time off, as of `a3def09a`.

**Comment by makitos666** [comment]
I've also been looking at the code to try to parallelize some part of the process. Unfortunately, since you use generators that generate generators that generate generators, etc. I have not found any alternative.

On the other hand I have seen that in higher execution times (hours), there is an important part of the time spent on Print. Maybe a buffer (as a parameter) could be implemented to be able to control all the information at once.

Thank you very much for your effort ;)

**Comment by ikelos** [comment]
Yeah, sorry.  It's designed to do what it can as fast as possible (which is generators) but they can get a bit out of hand.  5:S

When you say the time is spent on Print, do you mean on printkey?  It's not really printing, it's just determining the strings that should be output.  If you meant on sys.stdout.write, then you can reduce the time spent by directing the output to a file.  Sorry we haven't been able to get it faster, but hopefully the latest version is a good chunk faster.  You may however, get more benefit from exporting the files and reading them in a C program that reads hives directly?  At the moment, there's no glue to join up loading the registry layer and the layerwriter plugin that dumps a layer out to a file, but that should be all that's necessary to get a hive written out?  I may write a hivedump plugin that could do it...

**Comment by makitos666** [comment]
No, I don't mean prinykey. I say the "render" function in "text_renderer". The "visitor" is called for each registry line, and this function writes and flush the accumulator. 
I mean to make a buffer here to be able to write + flush every X Mb of information.

**Comment by ikelos** [comment]
Oh, I see.  Hmmm, that could speed it up I guess?  I'll try some experiments after I get the hivedumper working...  5:)

**Comment by ikelos** [comment]
Thinking about it more, we explicitly flush because python buffers by default and many investigators are impatient and want immediate results on the command line (it's also one of the reasons the treegrids use generators rather than running, so that when a result returns we can display it immediately).  You could try piping to a file, which should take out the time necessary to write to the console?

**Comment by ikelos** [comment]
It's not clear what more we can do on this front, so we're likely to close this issue.  We are still working on better parallelization, but for it's a much longer term issue I'm afraid.  If you think there's more we can do, please feel free to reopen this...
