### ISSUE TITLE
windows.pstree : TypeError: Values must be a list of objects made up of simple types and number the same as the columns

### ISSUE THREAD

**Issue by garanews** [volatilityfoundation/volatility3#330]
Just pulled repo and seen this:
```
python vol.py -f stuxnet.vmem windows.pstree
Volatility 3 Framework 1.2.0-beta.1
Progress:    0.00               Scanning primary2 using PdbSignatureScanner
PID     PPID    ImageFileName   Offset(V)       Threads Handles SessionId       Wow64   CreateTime      ExitTime        Dumped
Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\cli\text_renderer.py", line 181, in render
    grid.populate(visitor, outfd)
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 215, in populate
    treenode = self._append(parent, item)
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 276, in _append
    return self._insert(parent, len(children), values)
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 285, in _insert
    tree_item = TreeNode(newpath, self, parent, values)
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 59, in __init__
    self._validate_values(values)
  File "C:\Users\Gara\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 75, in _validate_values
    raise TypeError(
TypeError: Values must be a list of objects made up of simple types and number the same as the columns
```

python vol.py --version
Volatility 3 Framework 1.2.0-beta.1
What about start increasing numbering, like beta1, beta2 etc? (would be nice if create some tagged version)
In this way it will be easy to track version, what is working, what is changed, etc  :)

**Comment by ikelos** [comment]
Yep, this is one of the perils of inheritting plugins rather than having the dependency system we have.  Pstree is now not-inheritted and will work even if pslist changes, or let you know why if the pslist version isn't right.

To be fair, you're pulling individual git commits, so your identifier for which version is working is the git commit.  That's the cost of using the development repository as your live version.  As you can see the version of the framework has already been increased to 1.2.0 (and may soon jump to 2.0.0), but that's for the framework alone, not the plugins, so even that wouldn't help you that much.

Anyway, this should be fixed with `752a62a2`.  Please feel free to reopen this if you still encounter the issue.

**Comment by dadokkio** [comment]
I just tried to update the lib and now I see that the dump flag is gone but I still receive the same error. I receive the error when I try to put the plugin result in the treegrid renderer, from cli it works fine.

**Comment by ikelos** [comment]
@dadokkio Where is the tree grid getting its columns and numbers from?  The issue was that `pstree` was yield a certain number of results per row, but it was using `pslist` to get the TreeGrid to put them into, now it should have its own TreeGrid defined, and the plugin should be consistent internally (as in, it shouldn't matter the UI that's generating it).  Could you please verify the number of results that are yielded versus the size of the TreeGrid being used?

**Comment by dadokkio** [comment]
I'm using for all the plugins [a custom renderer ](https://gist.github.com/dadokkio/9411d7a2dae6fa19bf2e0d7cba5ad713) based on JsonRenderer that return partial results and error if it fails. For now I can see that the plugin is failing with the error provided and it's returning empty result. I'm going to run the code manually to understand what it's happening.

**Comment by dadokkio** [comment]
Ok, my fault.. using dask I need to update volatility in all the docker instances. So it's working.
The only parts missing is that the plugin does not work anymore on AMF_MemorySamples/windows/Sample001

```
(test_vola) dadokkio@Q:~/Documents/orochi/symbols/TEST$ vol -vv -f /home/dadokkio/Desktop/DOCKER/AMF_MemorySamples/windows/sample001.bin windows.pstree
Volatility 3 Framework 1.2.0-beta.1
INFO     root        : Volatility plugins path: ['/home/dadokkio/miniconda3/envs/test_vola/lib/python3.8/site-packages/volatility/plugins', '/home/dadokkio/miniconda3/envs/test_vola/lib/python3.8/site-packages/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/dadokkio/miniconda3/envs/test_vola/lib/python3.8/site-packages/volatility/symbols', '/home/dadokkio/miniconda3/envs/test_vola/lib/python3.8/site-packages/volatility/framework/symbols']
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.yarascan based on file: yarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.svcscan based on file: windows/svcscan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.vadyarascan based on file: windows/vadyarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.callbacks based on file: windows/callbacks
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.hashdump based on file: windows/hashdump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.lsadump based on file: windows/lsadump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.cachedump based on file: windows/cachedump
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.cachedump, volatility.plugins.windows.callbacks, volatility.plugins.windows.hashdump, volatility.plugins.windows.lsadump, volatility.plugins.windows.svcscan, volatility.plugins.windows.vadyarascan, volatility.plugins.yarascan
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
INFO     volatility.framework.automagic: Running automagic: LayerStacker
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x39000
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntoskrnl.pdb/47A5AC97343A4A7ABF14EFD9E9933772-2
INFO     volatility.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility.schemas: All validations will report success, even with malformed input
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x804d7000

PID     PPID    ImageFileName   Offset(V)       Threads Handles SessionId       Wow64   CreateTime      ExitTime
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
```
Then it remains stucked without any other feedback.

**Comment by ikelos** [comment]
Ok, that's very strange.  Really very little should have changed?  Can you let me know the two git commits (one that works and one that doesn't), and the output from when it did work please?

**Comment by dadokkio** [comment]
Ok, my fault again. I tried old commits (till beginning of august) and the response is the same.. probably picking sample randomly we didn't select this one before.

**Comment by ikelos** [comment]
That's fine, just want to make sure we don't overlook something that someone reported and then never fix it, thanks for the testing today!  5:)
